[theme]
base = "dark"
primaryColor = "#3da5ff"
backgroundColor = "#0e1217"
secondaryBackgroundColor = "#171c26"
textColor = "#d7dde5"
font = "sans serif"

[server]
headless = true
enableCORS = false
enableXsrfProtection = true

[browser]
gatherUsageStats = false
